/*
 * This source file was generated by the Skeletal project creation tool.
 * https://github.com/cbmarcum/skeletal
 */
package org.cland.alice.agent;

import org.cland.alice.core.Agent;

public class AliceAgent {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Agent agent=new Agent();
        agent.run();
        System.out.println(new AliceAgent().getGreeting());
    }
}
